# mypy.ini
[mypy]
python_version = 3.12
exclude_gitignore = True
num_workers = 8

# Strict
strict = True
strict_equality = True
strict_equality_for_none = True
strict_bytes = True

# Warnings
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
warn_unreachable = True
warn_incomplete_stub = True
warn_unused_configs = True

# Don't allow untyped code to slip in
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_calls = True
disallow_untyped_decorators = True

# Even when things are untyped still process
follow_untyped_imports = True
check_untyped_defs = True

# Extra hygiene
show_error_codes = True
pretty = True

# Future proofing
extra_checks = True